### ISSUE TITLE
do not work correctly

### ISSUE THREAD

**Issue by kingtosh** [smartmix/labeledPagesExporter#3]
I tried to use this script. but it did not work correctly, just appeared main panel.
There was no colour list panel. 
and I couldn't apply colour level to pages.

I'm using indesign CC 2017 or 2018 under MacOS 10.12, japanese environment.

**Comment by tizianovolpe** [comment]
The color label is a native function of indesign:
· Right click on the page you need to export
· go to page attributes > color label
· assign the color you prefer

When you assign the color to pages you can run the script and select which label you want to export

Here You can see a screenshot, I've the italian version CC 2017 but I think the japanese is similar.
![schermata 2018-03-09 alle 09 02 54](https://user-images.githubusercontent.com/25770035/37197166-0114f69e-237a-11e8-95b2-f99f6cc4bf31.png)

**Comment by kingtosh** [comment]
thanks smartmix.
that's my misunderstandings. your script work well.
